#Ide kell beilleszteni: /home/drszigetib/.local/share/xfce4/terminal/colorschemes/

[Scheme]
Name=Midnight Graphite
ColorForeground=#d8dee9
ColorBackground=#1e222a
ColorCursor=#88c0d0
ColorCursorUseDefault=FALSE
ColorSelectionBackground=#434c5e
ColorSelection=#eceff4

ColorPalette1=#2e3440
ColorPalette2=#bf616a
ColorPalette3=#a3be8c
ColorPalette4=#ebcb8b
ColorPalette5=#81a1c1
ColorPalette6=#b48ead
ColorPalette7=#88c0d0
ColorPalette8=#e5e9f0
ColorPalette9=#4c566a
ColorPalette10=#bf616a
ColorPalette11=#a3be8c
ColorPalette12=#ebcb8b
ColorPalette13=#81a1c1
ColorPalette14=#b48ead
ColorPalette15=#8fbcbb
ColorPalette16=#eceff4
